project_id = "llwexqpavwrkokstuedy"

[functions.rank-candidates]
verify_jwt = false

[functions.eligibility-check]
verify_jwt = false

[functions.extract-profile]
verify_jwt = false

[functions.parse-resume]
verify_jwt = false
